# - name: ping the server
#   hosts:  frontend # target server
#   tasks: # tasks == module == collection ==noor
#   - name: ping the server
#     ping: # ansible.builtin.ping

- name: Ping the server
  hosts: local
  connection: local
  tasks: 
  - name: Ping the server
    ping: