# - name: demo on debug
#   hosts: frontend
#   tasks:
#   - name: hello world
#     debug:
#       msg: "Hello Ansible!"

- name: demo for printing
  hosts: frontend
  tasks:
  - name: Hello world
    debug:
      msg: "I love Afrin"