# - name: print gather facts
#   hosts: frontend
#   tasks:
#   - name: print gathered facts
#     debug:
#       msg: "{{ ansible_facts }}"

- name: printing gather facts
  hosts: frontend
  tasks:
  - name: printing gather facts
    debug:
      msg: "{{ ansible_facts }}"