# - name: check number of live sessions
#   hosts: local
#   connection: local
#   vars:
#     live_sessions: 4
#   tasks:
#   - name: is ansible more than 5 sessions
#     debug:
#       msg: "Yes, Ansible took more than 5 sessions"
#     when: live_sessions > 5

- name: checking number of live_sessions
  hosts: local
  connection: local
  vars:
    live_sessions: 6
  tasks:
  - name: is ansible more than 5 sessions
    debug:
      msg: "yes, ansible tooks more than 5 sessions"
    when: live_sessions > 5