# - name: even or odd
#   hosts: local
#   connection: local
#   vars:
#     given_number: 8
#   tasks:
#   - when: given_number % 2 == 0
#     debug:
#       msg: "give number: {{ given_number }} is even"
#     name: is even
    
#   - name: is odd
#     debug:
#       msg: "give number: {{ given_number }} is odd"
#     when: given_number % 2 != 0

- name: checking even or odd
  hosts: local
  connection: local
  vars_prompt:
    name: number
    prompt: "Please enter the number: "
    private: false
  tasks:
  - name: is even
    debug:
      msg: "given number is {{ number }} even"
    when: (number | int) % 2 == 0
    
  - name: is odd
    debug:
      msg: "given number is {{ number }} odd"
    when: (number | int) % 2 != 0
    